- packages/theme/src/client/components/LayoutContent.vue
- packages/theme/src/client/layouts/NotFound.vue
> 修复存在 `sidebar` 时 404页面错位问题

- theme/src/client/components/Nav/VPNavBarTitle.vue
修正logo高度未使用预定义设置（--vp-nav-logo-height），造成logo高度无法被覆写修改的问题。
> feat(theme): add custom height support for the navbar logo  

- theme/src/client/index.ts
> perf(theme): improve theme exports, close #215

- theme/src/node/prepare/prepareBlogData.ts
- theme/src/shared/frontmatter/post.ts
> feat(theme): add support frontmatter `excerpt` for blog post, close #218

- cli/package.json
- cli/src/generate.ts
- cli/src/packageJson.ts
- cli/src/run.ts
- plugins/plugin-md-power/package.json
- pnpm-lock.yaml
> fix(cli): incorrect `yarn` project creation process, close #254

- theme/src/client/composables/outline.ts
- theme/src/client/utils/shared.ts
> fix(theme): incorrect anchor link scrolling, close #266

- theme/src/client/components/Nav/VPNav.vue
- theme/src/client/styles/vars.css
> fix(theme): incorrect page layout when `navbar: false`, close #270

- docs/notes/theme/config/主题配置.md
- theme/src/client/components/Blog/VPBlogCategories.vue
- theme/src/client/components/Blog/VPCategories.vue
- theme/src/client/components/Blog/VPCategoriesGroup.vue
- theme/src/client/composables/blog-category.ts
- theme/src/shared/blog.ts
> feat(theme): add support for blog category expand depth, close #271

- docs/notes/theme/config/主题配置.md
- theme/src/client/components/VPDocMeta.vue
- theme/src/shared/options/locale.ts
> feat(theme): add support for whether to display `createTime`, close #279

- theme/src/node/prepare/prepareArticleTagColor.ts
> fix(theme): incorrect prepared with tags's temp files, close #286

- theme/src/node/config/extendsBundlerOptions.ts
> fix(theme): silent sass `@import` deprecation warning, close #291

- theme/src/client/components/Home/VPHomeHero.vue
> fix(theme): incorrect home hero background styles, close #304

- theme/src/client/composables/sidebar.ts
- theme/src/client/shim.d.ts
- theme/src/node/prepare/prepareSidebar.ts
- theme/src/shared/options/bulletin.ts
> fix(theme): incorrect auto generate sidebar, close #307

- theme/src/client/components/global/VPLinkCard.vue
> fix(theme): incorrect layer for `LinkCard` icon, close #310

- theme/src/client/components/Blog/VPPostItem.vue
- theme/src/client/components/VPDocMeta.vue
> fix(theme): incorrect time format, close #312

- theme/src/client/components/Blog/VPBlogArchives.vue
- theme/src/client/composables/blog-archives.ts
- theme/src/node/locales/en.ts
- theme/src/node/locales/zh.ts
- theme/src/shared/base.ts
> feat(theme): add archive article count, close #326

- docs/notes/theme/config/主题配置.md
- theme/src/client/components/VPSwitchAppearance.vue
- theme/src/client/composables/dark-mode.ts
- theme/src/shared/base.ts
> feat(theme): optimize appearance transition, close #325

- theme/src/client/features/composables/github-repo.ts
github repo 卡片的请求量增长速度明显，预估很快达到 免费额度的阈值。
通过请求日志发现，绝大部分请求均时短时间内的重复请求，且经常来源相同。
github-repo 的请求数据现在使用 localStroage 进行缓存，过期时间为 6 个小时。
> feat(theme): add repo card cache

- docs/demos.md
Replace static images with remote links.
> docs: update `demos.md`

- theme/src/node/config/resolveProvideData.ts
> fix(theme): locales preset injection failed, close #354

- theme/src/client/components/VPDocCopyright.vue
> fix(theme): incorrect article copyright, close #362

- theme/src/client/components/VPDocBreadcrumbs.vue
> fix(theme): incorrect `link` parsing in breadcrumb nav, close #369

- docs/notes/theme/config/plugins/阅读统计.md
- docs/notes/theme/config/主题配置.md
- docs/notes/theme/guide/功能/图标.md
> docs: improve docs

- theme/src/client/features/components/Swiper.vue
> fix(theme): fix carousel swiper that stops unexpectedly during appearance switching

- theme/src/node/prepare/prepareSidebar.ts
> fix(theme): incorrect sidebar auto sorting, close #387

- theme/src/client/styles/normalize.css
- theme/src/node/plugins/getPlugins.ts
> fix(theme): incorrect `font-synthesis` and `readingTime` format

- docs/demos.md
> docs: add `city walk` demos

- docs/notes/tools/README.md
fix(docs): notes/tools/README.md 404
> fix(docs): notes/tools/README.md 404

- docs/demos.md
> docs: add ohmymc

- theme/src/client/composables/langs.ts
> fix(theme): incorrect langs switch in blog page, close #404

- docs/demos.md
> docs: add `QiHuang02` demo

- plugins/plugin-md-power/src/client/styles/steps.css
> fix(plugin-md-power): improve steps styles, close #422

- theme/src/client/components/VPFooter.vue
> fix(theme): fix flickering white border in bottom of home, close #424

- plugins/plugin-md-power/src/client/components/CodeTabs.vue
- theme/src/client/styles/code.css
> fix(theme): improve code block scrollbar, close #427

- theme/src/client/components/VPDoc.vue
> fix(theme): improve page aside layout, close #429

- theme/src/client/composables/copyright.ts
> fix(theme): incorrect copyright author, close #443

- plugins/plugin-shikiji/src/node/utils/whitespace.ts
> fix(plugin-shikiji): incorrect render when `whitespace:true`, close #444

- docs/notes/theme/config/主题配置.md
- theme/src/client/components/VPSidebar.vue
- theme/src/shared/options/locale.ts
> feat(theme): add `sidebarScrollbar` options, close #425

- docs/demos.md
add my website
我是一名来自 THU 的物理系学生，这个网站是作为一个爱好运营的，希望您能够通过. 同时感谢您的 plume 主题！
> docs: add `physnya.top` demo

- theme/src/client/composables/outline.ts
> fix: `abbr` incorrectly rendered in `toc`, close #488

- theme/src/client/components/VPDoc.vue
- theme/src/client/components/VPLocalNav.vue
> fix(theme): incorrect toc display in 1200px screen, close #493

- theme/src/client/composables/outline.ts
> fix(theme): incorrect calculation of active link in the outline, close #492

- theme/src/client/composables/dark-mode.ts
> fix(theme): page should be in light mode while printing, close #502

- CONTRIBUTING.en-US.md
- CONTRIBUTING.md
- cli/templates/.vuepress/config.ts.handlebars
- docs/.vuepress/config.ts
- docs/.vuepress/notes/zh/theme-guide.ts
- docs/notes/theme/config/theme.md
- docs/notes/theme/guide/features/replace-assets.md
- plugins/plugin-replace-assets/LICENSE
- plugins/plugin-replace-assets/__test__/__snapshots__/transform.spec.ts.snap
- plugins/plugin-replace-assets/__test__/normalizeRules.spec.ts
- plugins/plugin-replace-assets/__test__/transform.spec.ts
- plugins/plugin-replace-assets/__test__/unplugin-utils.spec.ts
- plugins/plugin-replace-assets/package.json
- plugins/plugin-replace-assets/src/constants.ts
- plugins/plugin-replace-assets/src/index.ts
- plugins/plugin-replace-assets/src/normalizeRules.ts
- plugins/plugin-replace-assets/src/options.ts
- plugins/plugin-replace-assets/src/plugin.ts
- plugins/plugin-replace-assets/src/unplugin/factory.ts
- plugins/plugin-replace-assets/src/unplugin/index.ts
- plugins/plugin-replace-assets/src/unplugin/transform.ts
- plugins/plugin-replace-assets/src/unplugin/utils.ts
- plugins/plugin-replace-assets/tsup.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- theme/package.json
- theme/src/node/detector/fields.ts
- theme/src/node/plugins/setupPlugins.ts
- theme/src/shared/options.ts
- theme/src/shared/plugins.ts
#545
不少 vuepress 的用户会使用图床服务来加速站点的图片资源访问。
此插件检测 vuepress 代码中的本地资源地址，通过规则，将它们替换为新的资源地址。
```ts
import { replaceAssetsPlugin } from 'vuepress-plugin-replace-assets
export default defineUserConfig({
// ...
plugins: [
replaceAssetsPlugin('https://example.com')
],
// ...
})
```
```ts
import { replaceAssetsPlugin } from 'vuepress-plugin-replace-assets
export default defineUserConfig({
// ...
plugins: [
replaceAssetsPlugin({
image: 'https://example.com/images',
media: 'https://example.com/medias',
})
],
// ...
})
```
```ts
import { replaceAssetsPlugin } from 'vuepress-plugin-replace-assets
export default defineUserConfig({
// ...
plugins: [
replaceAssetsPlugin((url) => 'https://example.com' + url)
],
// ...
})
```
```ts
import { replaceAssetsPlugin } from 'vuepress-plugin-replace-assets
export …
```
> feat: add `vuepress-plugin-replace-assets` support, close #545

- docs/en/notes/theme/guide/quick-start/usage.md
- docs/notes/theme/guide/quick-start/usage.md
- package.json
- plugins/plugin-fonts/tsup.config.ts
- plugins/plugin-md-power/tsup.config.ts
- plugins/plugin-replace-assets/tsup.config.ts
- plugins/plugin-search/tsup.config.ts
- theme/package.json
- theme/tsup.config.ts
- tsconfig.base.json
> feat!: drop `node18` support, close #574

- docs/notes/theme/guide/markdown/file-tree.md
- plugins/plugin-md-power/__test__/__snapshots__/fileTreePlugin.spec.ts.snap
- plugins/plugin-md-power/__test__/fileTreePlugin.spec.ts
- plugins/plugin-md-power/src/client/components/FileTreeNode.vue
- plugins/plugin-md-power/src/node/container/fileTree.ts
> feat(plugin-md-power): add diff syntax in file-tree container, close #577

- docs/.vuepress/notes/zh/theme-guide.ts
- docs/.vuepress/theme.ts
- docs/notes/theme/config/markdown.md
- docs/notes/theme/guide/markdown/field.md
- plugins/plugin-md-power/src/client/components/VPField.vue
- plugins/plugin-md-power/src/node/container/field.ts
- plugins/plugin-md-power/src/node/container/index.ts
- plugins/plugin-md-power/src/node/prepareConfigFile.ts
- plugins/plugin-md-power/src/shared/plugin.ts
- theme/src/node/detector/fields.ts
> feat(plugin-md-power): add `field` and `field-group` container, close #566

- docs/.vuepress/notes/zh/theme-guide.ts
- docs/.vuepress/theme.ts
- docs/notes/theme/guide/markdown/code-tree.md
- plugins/plugin-md-power/__test__/resolveAttrs.spec.ts
- plugins/plugin-md-power/package.json
- plugins/plugin-md-power/src/client/components/FileTreeNode.vue
- plugins/plugin-md-power/src/client/components/VPCodeTree.vue
- plugins/plugin-md-power/src/node/container/codeTree.ts
- plugins/plugin-md-power/src/node/container/fileTree.ts
- plugins/plugin-md-power/src/node/container/index.ts
- plugins/plugin-md-power/src/node/plugin.ts
- plugins/plugin-md-power/src/node/prepareConfigFile.ts
- plugins/plugin-md-power/src/node/utils/resolveAttrs.ts
- plugins/plugin-md-power/src/shared/codeTree.ts
- plugins/plugin-md-power/src/shared/plugin.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- theme/src/client/styles/code.css
- theme/src/node/detector/fields.ts
- theme/src/node/plugins/code.ts
> feat(plugin-md-power): add code-tree container and embed syntax, close #567

- plugins/plugin-md-power/src/client/components/VPCodeTree.vue
> fix(plugin-md-power): incorrect collapsed lines in code-tree, close #587

- docs/demos.md
> docs: add `手动互感` to demos

- plugins/plugin-md-power/__test__/linksPlugin.spec.ts
- plugins/plugin-md-power/src/node/enhance/links.ts
> feat(plugin-md-power): add `links` to markdown env, close #626

- theme/src/client/components/Nav/VPNavBarTranslations.vue
- theme/src/client/components/Nav/VPNavScreenTranslations.vue
- theme/src/client/composables/langs.ts
> fix(theme): locales selector not rendering correctly on mobile, close #640

- cli/templates/.vuepress/config.ts.handlebars
- docs/.vuepress/notes/zh/theme-guide.ts
- docs/.vuepress/theme.ts
- docs/notes/theme/guide/markdown/table.md
- plugins/plugin-md-power/src/client/components/VPTable.vue
- plugins/plugin-md-power/src/node/container/index.ts
- plugins/plugin-md-power/src/node/container/table.ts
- plugins/plugin-md-power/src/node/prepareConfigFile.ts
- plugins/plugin-md-power/src/shared/plugin.ts
- plugins/plugin-md-power/src/shared/table.ts
- theme/src/node/detector/fields.ts
> feat(plugin-md-power): add `table` container, close #652

- plugins/plugin-md-power/src/client/components/FileTreeNode.vue
> fix(plugin-md-power): fix title overflow in file-tree, close #698

- theme/src/node/prepare/prepareBlogData.ts
> fix(theme): fix `createTime` is obtained incorrectly during creation, close #692
